# Generated by Django 2.1 on 2018-08-29 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('name', models.TextField(max_length=255)),
                ('done', models.BooleanField(blank=True, default=False)),
                ('mark', models.BooleanField(blank=True, default=False)),
                ('repeater', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('name', models.TextField(max_length=255)),
                ('done', models.BooleanField(blank=True, default=False)),
                ('mark', models.BooleanField(blank=True, default=False)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('deadline', 'updated', 'created'),
            },
        ),
        migrations.AddField(
            model_name='action',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Goal'),
        ),
    ]
